name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    #Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v2

    #Setup Node.js
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: cd season_checker-frontend
    - run: npm install react-scripts --save
    - run: npm install -g npm@8.18.0
        
    - name: Install dependencies
      run: npm install

    #Run Test
    #- name: Run the tests
      #run: npm run test


  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    #Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v2

    #Setup Node.js
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd season_checker-frontend
        npm install

    #Build
    - name: Build
      run: npm run build
