name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    #Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v2

    #Setup Node.js
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd season_checker-frontend
        npm install

    #Run Test
    - name: Run the tests
      run: |
        cd season_checker-frontend
        npm test


  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    #Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v2

    #Setup Node.js
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: |
        cd season_checker-frontend
        npm install

    #Build
    - name: Build
      run: |
        cd season_checker-frontend
        npm run build
        
    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: buildJS
        path: build
